// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkwpyTsQjhZGWQNMtDtBlbFvGhXTJLJ5k',
    appId: '1:128578854417:web:1b8ac3a0c4e3e5cd941bb0',
    messagingSenderId: '128578854417',
    projectId: 'chat-app-e9737',
    authDomain: 'chat-app-e9737.firebaseapp.com',
    storageBucket: 'chat-app-e9737.appspot.com',
    measurementId: 'G-G292TV99B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB7-7iMmPUJXezkfpJj7z-OuOtjBCXoEI',
    appId: '1:128578854417:android:d881fc1df708dbc6941bb0',
    messagingSenderId: '128578854417',
    projectId: 'chat-app-e9737',
    storageBucket: 'chat-app-e9737.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5AvYVUEzg9qFrkyUeahlVtRPDTsScN_o',
    appId: '1:128578854417:ios:f05abb418827abac941bb0',
    messagingSenderId: '128578854417',
    projectId: 'chat-app-e9737',
    storageBucket: 'chat-app-e9737.appspot.com',
    iosClientId: '128578854417-54qa8dtapv434cka791gl2f7iv80ja5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
